name: Angular init

on:
  workflow_dispatch:

jobs:
  Initialization:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Seting up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Installing Angular CLI
        run: npm install @angular/cli

      - name: Chcking versions
        run: |
          npm --version
          npm ng --version
          node --version
