name: Angular init

on:

  workflow_dispatch:

jobs:

  Initialization:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Installing packages and depencies for Angular Application 
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          apt-get update
          apt-get install -y nodejs npm
          npm install -g @angular/cli
          ng --version && npm --version
