name: Angular Continuous Integration

on:
  push:
    branches:
      - Development

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Go to app folder
      run: |
        cd angular-app/

    - name: Seting up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build

    - name: Run tests
      run: npm run test
