name: Angular Continuous Integration

on:
  push:
    branches:
      - Development

jobs:

  Tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Seting up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'

    - name: Install dependencies
      run: npm install
      working-directory: ${{ github.workspace }}/angular-app

    - name: Build Angular app
      run: npm run build
      working-directory: ${{ github.workspace }}/angular-app
      
    - name: Run tests with Chrome Headless
      run: |
        timeout 3m npm run test -- --browsers=ChromeHeadless
      working-directory: ${{ github.workspace }}/angular-app


