name: Create Tag
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create git tag
        uses: P4dr4/create-git-tag-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: 'v1.0.0'
          override: 'true'
