name: Create Tag
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if tag exists
        id: check_tag
        run: |
          if git rev-parse "v1.0.0" >/dev/null 2>&1; then
            echo "::set-output name=tag_exists::true"
          else
            echo "::set-output name=tag_exists::false"
          fi

      - name: Create git tag
        if: steps.check_tag.outputs.tag_exists != 'true'
        uses: P4dr4/create-git-tag-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: 'v1.0.0'
          override: 'true'
